
default: &default
  adapter: postgresql
  pool: 5

development:
  <<: *default
  database: withinMeans_development

test:
  <<: *default
  database: withinMeans_test

production:
  <<: *default
  database: withinMeans_production
  username: withinMeans
  password: <%= ENV['WITHINMEANS_DATABASE_PASSWORD'] %>
